// config_init.go owns the guided `config init` setup wizard. It runs only when
// stdin is a real terminal; pipes, redirects and scripts keep the original
// static-template behavior (see CmdConfig). The wizard derives everything from
// the two authoritative sources — the annotated template
// (configdomain.DefaultConfigYAML) for provider blocks/routes and the takeover
// package for client config paths — so no provider or path knowledge is
// duplicated here.
package config

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/mattn/go-isatty"
	"gopkg.in/yaml.v3"

	cliframework "model-proxy/internal/cli/framework"
	configdomain "model-proxy/internal/config"
	"model-proxy/internal/provider"
	"model-proxy/internal/takeover"
)

// configInitInteractive reports whether `config init` should run the guided
// wizard. A real terminal (ioctl-verified, so /dev/null and pipes don't count)
// on stdin opts in; everything else keeps the static template write.
func configInitInteractive() bool {
	fd := os.Stdin.Fd()
	return isatty.IsTerminal(fd) || isatty.IsCygwinTerminal(fd)
}

// initProviderDoc / initRouteDoc / initConfigDoc are the marshal shapes for the
// minimal config the wizard writes — omitempty keeps the output free of the
// zero-value noise the full template annotates by hand.
type initProviderDoc struct {
	OpenAIBaseURL    string            `yaml:"openai_base_url"`
	AnthropicBaseURL string            `yaml:"anthropic_base_url,omitempty"`
	ProviderID       string            `yaml:"provider_id"`
	Priority         int               `yaml:"priority,omitempty"`
	AqpMintURL       string            `yaml:"aqp_mint_url,omitempty"`
	UsageURL         string            `yaml:"usage_url,omitempty"`
	Billing          string            `yaml:"billing,omitempty"`
	Alias            map[string]string `yaml:"alias,omitempty"`
	Models           []string          `yaml:"models"`
}

type initConfigDoc struct {
	Listen    string                     `yaml:"listen"`
	Providers map[string]initProviderDoc `yaml:"providers"`
}

const initConfigHeader = `# model-proxy config — generated by the interactive ` + "`config init`" + ` wizard.
# Only the providers you selected are included. For the fully annotated
# template (scheduling, cache, shadow, fusion, ...), run ` + "`config init`" + `
# with stdin redirected (e.g. ` + "`model-proxy config init < /dev/null`" + `).

`

// runConfigInitWizard guides the user through client detection, provider
// selection and takeover, then writes a minimal config.yaml in the CWD.
// in/out are injected so tests can drive the interaction without a terminal.
func runConfigInitWizard(in io.Reader, out io.Writer) error {
	tpl, err := configdomain.LoadConfigFromBytes("config.yaml", []byte(configdomain.DefaultConfigYAML))
	if err != nil {
		return fmt.Errorf("built-in config template is invalid: %w", err)
	}
	r := bufio.NewReader(in)

	fmt.Fprintln(out, "model-proxy config init — guided setup")
	fmt.Fprintln(out)

	// 1. Detect installed coding clients via the takeover package's template
	// path knowledge (template file defaults == standard client config
	// locations). Template resolution failures just mean "nothing detected".
	// Detection dedupes to one entry per client family — protocol variants
	// of a family share the same config file, and the variant is chosen at
	// takeover time against the written config (native-protocol selection).
	var detected []takeover.ClientSpec
	seenFamily := map[string]bool{}
	if clients, err := takeover.ListClients(tpl, "all", ""); err == nil {
		for _, c := range clients {
			family := c.Template.ClientFamily()
			if seenFamily[family] {
				continue
			}
			if _, err := os.Stat(c.File); err == nil {
				seenFamily[family] = true
				c.Name = family
				detected = append(detected, c)
			}
		}
	}
	if len(detected) > 0 {
		fmt.Fprintln(out, "Detected client configs:")
		for _, c := range detected {
			fmt.Fprintf(out, "  %-10s %s\n", c.Name, c.File)
		}
	} else {
		fmt.Fprintln(out, "No coding client configs detected (claude/opencode/codex/pi).")
	}
	fmt.Fprintln(out)

	// 2. Provider selection: template provider blocks, filtered to ids with a
	// registered implementation.
	var names []string
	for name, p := range tpl.Providers {
		if provider.IsRegistered(p.Provider) {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	fmt.Fprintln(out, "Which providers do you want to enable?")
	selected := map[string]bool{}
	for _, name := range names {
		p := tpl.Providers[name]
		if askYesNo(r, out, fmt.Sprintf("Enable %s (provider=%s, %d models)? [y/N] ", name, p.Provider, len(p.Models))) {
			selected[name] = true
		}
	}
	if len(selected) == 0 {
		return errors.New("no providers selected — config.yaml not written")
	}

	// 3. Write the minimal config.
	data, testModel, err := renderInitConfig(tpl, selected)
	if err != nil {
		return err
	}
	if err := os.WriteFile("config.yaml", data, 0o644); err != nil {
		return err
	}
	var selNames []string
	for name := range selected {
		selNames = append(selNames, name)
	}
	sort.Strings(selNames)
	fmt.Fprintf(out, "\nwrote config.yaml (%d providers: %s)\n", len(selNames), strings.Join(selNames, ", "))

	// 4. Offer takeover right away for detected clients (idempotent backup).
	tookOver := false
	if len(detected) > 0 {
		var clientNames []string
		for _, c := range detected {
			clientNames = append(clientNames, c.Name)
		}
		if askYesNo(r, out, fmt.Sprintf("Take over detected client configs now (%s)? [y/N] ", strings.Join(clientNames, ", "))) {
			tookOver = true
			cfg, err := configdomain.LoadConfig("config.yaml")
			if err != nil {
				return fmt.Errorf("reload written config: %w", err)
			}
			for _, c := range detected {
				if err := takeover.RunTakeover(cfg, c.Name, takeover.BackupDir("config.yaml"), takeover.ModelFactsFor(cfg, c.Name, cliframework.HomeDir(), ""), ""); err != nil {
					fmt.Fprintf(os.Stderr, "takeover %s failed: %v\n", c.Name, err)
				}
			}
		}
	}

	// 5. Next steps, last thing on screen.
	fmt.Fprintln(out, "\nNext steps:")
	for _, name := range selNames {
		fmt.Fprintf(out, "  model-proxy login %s\n", name)
	}
	if len(detected) > 0 && !tookOver {
		for _, c := range detected {
			fmt.Fprintf(out, "  model-proxy takeover %s\n", c.Name)
		}
	}
	fmt.Fprintln(out, "  model-proxy serve")
	fmt.Fprintf(out, "  model-proxy test %s\n", testModel)
	return nil
}

// askYesNo prints prompt, reads one line, and returns true only for an
// explicit y/yes. EOF (truncated input) defaults to no — fail-closed.
func askYesNo(r *bufio.Reader, out io.Writer, prompt string) bool {
	fmt.Fprint(out, prompt)
	line, err := r.ReadString('\n')
	if err != nil && line == "" {
		return false
	}
	line = strings.ToLower(strings.TrimSpace(line))
	return line == "y" || line == "yes"
}

// renderInitConfig builds the minimal config.yaml: selected provider blocks
// verbatim from the template (priority + alias included — routes are derived
// from them at runtime). The rendered bytes are re-validated before
// returning (fail-closed on a template drift that would produce an unloadable
// config). It also returns a concrete model name for the closing
// `model-proxy test` hint (first surviving exposed name).
func renderInitConfig(tpl *configdomain.Config, selected map[string]bool) (data []byte, testModel string, err error) {
	doc := initConfigDoc{
		Listen:    tpl.Listen,
		Providers: map[string]initProviderDoc{},
	}
	// Exposed names derivable from the SELECTED providers only.
	exposed := map[string]bool{}
	for name, p := range tpl.Providers {
		if !selected[name] {
			continue
		}
		doc.Providers[name] = initProviderDoc{
			OpenAIBaseURL:    p.OpenAIBaseURL,
			AnthropicBaseURL: p.AnthropicBaseURL,
			ProviderID:       p.Provider,
			Priority:         p.Priority,
			AqpMintURL:       p.AqpMintURL,
			UsageURL:         p.UsageURL,
			Billing:          p.Billing,
			Alias:            p.Alias,
			Models:           p.Models,
		}
		for _, m := range p.Models {
			exposed[p.ExposedModelName(m)] = true
		}
	}
	body, err := yaml.Marshal(doc)
	if err != nil {
		return nil, "", err
	}
	data = append([]byte(initConfigHeader), body...)
	if _, err := configdomain.LoadConfigFromBytes("config.yaml", data); err != nil {
		return nil, "", fmt.Errorf("generated config failed validation: %w", err)
	}
	if len(exposed) > 0 {
		// Deterministic hint: the first model of the alphabetically-first
		// selected provider (exposed name with alias applied).
		var names []string
		for name := range selected {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			if models := tpl.Providers[name].Models; len(models) > 0 {
				testModel = tpl.Providers[name].ExposedModelName(models[0])
				break
			}
		}
	} else {
		// No provider model exposed (empty model lists): fall back to any
		// provider name; routes appear once models are configured.
		var names []string
		for name := range selected {
			names = append(names, name)
		}
		sort.Strings(names)
		if len(names) > 0 {
			testModel = names[0]
		} else {
			testModel = "<model>"
		}
	}
	return data, testModel, nil
}
